config/routes.rb
Rails.application.routes.draw do
  get "/dashboard" => 'dashboard#index', as: :dashboard

  resources :properties
  devise_for :accounts
  get 'public/main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'public#main'
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable

  has_many :properties

  def full_name
    #{first_name} #{last_name}
  end

  def company
    "test company"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
    mount_uploader :photo, PhotoUploader
    belongs_to :account
    
    
    scope :latest, -> { order created_at: :desc }
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:update, keys: [:first_name, :last_name, :url])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_sidebar
  
  def index
  end

  private
  def set_sidebar
    @show_sidebar = true
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!, only: [:new, :create, :destroy]
  before_action :set_sidebar, except: [:show]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @agent = @property.account
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)
    @property.account_id = current_account.id

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    def set_sidebar
      @show_sidebar = true
    end
    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:name, :address, :price, :rooms, :bathrooms, :photo, :photo_cache)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def main
    @properties = Property.latest
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper

    def property_thumbnail (property)
        img = property.photo.present? ? property.photo.thumb.url : "placeholder.jpg"
        image_tag img, class: "property-thumb"
    end

    def property_photo_url (property)
        property.photo.present? ? property.photo.url : asset_url("placeholder.jpg") 
    end
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/dashboard/index.html.erb
     <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center  mb-3 border-bottom">
            <h1 class="h2">Dashboard</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
                This week
              </button>
            </div>
          </div>

   
          <h2>Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>

              </tbody>
            </table>
          </div>
       

app/views/dashboard/properties.html.erb
<h1>Dashboard#properties</h1>
<p>Find me in app/views/dashboard/properties.html.erb</p>

app/views/dashboard/reports.html.erb
<h1>Dashboard#reports</h1>
<p>Find me in app/views/dashboard/reports.html.erb</p>

app/views/layouts/_validation.html.erb
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealEstate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
   <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,700;1,100;1,300;1,700&display=swap" rel="stylesheet"> 
  </head>

  <body id="<%= controller.controller_name %>" class="<%= controller.action_name %> <%= "show-sidebar" if @show_sidebar.present? %>">
  <% if @show_sidebar.nil? %>
    <header>
      <%= render "layouts/nav/public" %>
        <%= yield %>
    </header>
  <% else %>
    <%= render "layouts/nav/dashboard" %>
 
   
    <div class="container">
      <div class="row">
       <%= render "layouts/nav/sidebar" %>
       <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4 mt-4">
         <%= yield %>
       </main>
      </div>
    </div>
 <% end %>
   <%#= render "layouts/nav/footer" %> 

  <div id="notifications"> <%= notice %> </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>
  </body>
</html>

app/views/layouts/nav/_dashboard.html.erb
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/">Real Estate</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
         <%= link_to "Log out", destroy_account_session_path, method: :delete, class:"nav-link" %>
        </li>
      </ul>
    </nav>

app/views/layouts/nav/_footer.html.erb
<footer class="container">
      <p>&copy; Real Estate finder 2020</p>
    </footer>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <%= link_to "Real Estate Finder", root_path, class:"navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
          <% if account_signed_in? %>
            <%= link_to "Dashborad", dashboard_path, class:"nav-link" %>
            <% else %>
            <%= link_to "Home", root_path, class:"nav-link" %>
            <% end %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Latest</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">News</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Advertising</a>
          </li>
          <% if account_signed_in? %>
           <li class="nav-item">
            <%= link_to "Log out", destroy_account_session_path, method: :delete, class:"nav-link" %>
          </li>
          <% else %>
           <li class="nav-item">
            <%= link_to "Log In", new_account_session_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign Up", new_account_registration_path, class:"nav-link" %>
          </li>
          <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

app/views/layouts/nav/_sidebar.html.erb
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to dashboard_path, class:"nav-link" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                  Dashboard <span class="sr-only">(current)</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to properties_path, class:"nav-link" do %>
                <i data-feather="package"></i>
                  Properties
               <% end %>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                <i data-feather="gift"></i>
                  Products
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                  Customers
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
                  Reports
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
                  Integrations
                </a>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Saved reports</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                  Current month
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                  Last quarter
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                  Social engagement
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                  Year-end sale
                </a>
              </li>
            </ul>
          </div>
        </nav>

app/views/properties/_agent_details.html.erb
<div class="">
    <h3 class="h4"><%= @agent.full_name %></h3>
    <p> <%= @agent.company %> </p>
    
    <button class="btn btn-info text-uppercase"> Call now</button>
    <button class="btn btn-success text-uppercase"> Email for more details </button>
</div>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>

<%= render "layouts/validation", item: @property %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class:"form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :rooms %>
    <%= form.number_field :rooms, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :bathrooms %>
    <%= form.number_field :bathrooms, class:"form-control" %>
  </div>

    <div class="form-group">
    <%= form.label :photo %>
    <%= form.file_field :photo, class:"form-control" %>
    <%= form.hidden_field :photo_cache %>
    <% if @property.photo.present? %>
      <%= image_tag @property.photo.thumb.url %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.submit "Save property", class:"btn  btn-success " %>
  </div>
<% end %>

app/views/properties/_latest_properties.html.erb
 <% @properties.each do |property| %>
    <div class="col-md-4">
        <%= link_to(property_thumbnail(property), property_path(property)) %>
        <h3><%=  link_to property.name, property_path(property) %></h3>
        <p><%= property.address %></p>
    </div>
  <% end %>

app/views/properties/edit.html.erb
<h1 class="h3">Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |

app/views/properties/index.html.erb
<h1 class="h3">Properties</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Price</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.address %></td>
        <td><%= property.price %></td>
        <td><%= property.rooms %></td>
        <td><%= property.bathrooms %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path, class:"btn btn-info" %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

app/views/properties/show.html.erb
  <div class="property-main-photo" style="background-image:url('<%= property_photo_url(@property) %>')">
    <div class="photo-overlay">
    </div> 
  </div>
 <div class="container">
      <div class="row">
        <div class="col-8">

              

            <p>
              <strong>Name:</strong>
              <%= @property.name %>
            </p>

            <p>
              <strong>Address:</strong>
              <%= @property.address %>
            </p>

            <p>
              <strong>Price:</strong>
              <%= @property.price %>
            </p>

            <p>
              <strong>Rooms:</strong>
              <%= @property.rooms %>
            </p>

            <p>
              <strong>Bathrooms:</strong>
              <%= @property.bathrooms %>
            </p>
            
            <%= link_to 'Edit property', edit_property_path(@property), class:"btn" %> 
        
        </div>
        <div class="col-4">
          <%= render "properties/agent_details" %>
        </div>
    </div>
</div>